apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: fake@gmail.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: password
        - name: postgres
          image: postgres
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "pg_isready -U user -d postgres"
            initialDelaySeconds: 5  # Wait before first check
            periodSeconds: 3         # Check every 3s
            timeoutSeconds: 3        # Timeout per check
            failureThreshold: 5      # Fail if unready 5 times
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "pg_isready -U user -d postgres"
            initialDelaySeconds: 10  # Start checking after 10s
            periodSeconds: 5         # Check every 5s
            timeoutSeconds: 5        # Timeout per check
            failureThreshold: 5      # Restart if unresponsive
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: 'user'
            - name: POSTGRES_PASSWORD
              value: 'password'
            - name: POSTGRES_DB
              value: 'postgres'
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: db-pvc # Uses the PVC instead of `emptyDir`

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432 # Service port (internal cluster)
      targetPort: 5432 # PostgreSQL container port
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Adjust the size as needed

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 80 # Service port (internal cluster)
      targetPort: 80 # PostgreSQL container port
  type: NodePort
